# Generated by Django 6.0.2 on 2026-02-12 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('badge', models.CharField(choices=[('Fine Dining', 'Fine Dining'), ('Casual Dining', 'Casual Dining'), ('Fast Food', 'Fast Food'), ('Cafe', 'Cafe')], max_length=50)),
                ('cuisine_type', models.CharField(help_text='e.g., Italian, Chinese, Indian, Mexican', max_length=100)),
                ('price_range', models.CharField(choices=[('$', 'Budget-Friendly'), ('$$', 'Moderate'), ('$$$', 'Expensive'), ('$$$$', 'Very Expensive')], default='$$', max_length=10)),
                ('average_cost_for_two', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_tables', models.PositiveIntegerField(default=10, help_text='Total number of tables available in the restaurant')),
                ('description', models.TextField()),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('image', models.ImageField(upload_to='restaurants/')),
                ('menu_image', models.ImageField(blank=True, null=True, upload_to='restaurants/menus/')),
                ('interior_image', models.ImageField(blank=True, null=True, upload_to='restaurants/interiors/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TableReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateField()),
                ('reservation_time', models.TimeField()),
                ('number_of_guests', models.PositiveIntegerField(default=2)),
                ('tables_reserved', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='confirmed', max_length=20)),
                ('special_requests', models.TextField(blank=True, help_text='Any special requests or dietary restrictions', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurants.restaurantdatamodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
