# Generated by Django 6.0.2 on 2026-02-17 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantdatamodel',
            name='average_cost_for_two',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantdatamodel',
            name='badge',
            field=models.CharField(blank=True, choices=[('Fine Dining', 'Fine Dining'), ('Casual Dining', 'Casual Dining'), ('Fast Food', 'Fast Food'), ('Cafe', 'Cafe')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantdatamodel',
            name='cuisine_type',
            field=models.CharField(blank=True, help_text='e.g., Italian, Chinese, Indian, Mexican', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantdatamodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/'),
        ),
        migrations.AlterField(
            model_name='restaurantdatamodel',
            name='price_range',
            field=models.CharField(blank=True, choices=[('$', 'Budget-Friendly'), ('$$', 'Moderate'), ('$$$', 'Expensive'), ('$$$$', 'Very Expensive')], default='$$', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='restaurantdatamodel',
            name='total_tables',
            field=models.PositiveIntegerField(blank=True, default=10, help_text='Total number of tables available in the restaurant', null=True),
        ),
    ]
