# Generated by Django 6.0.2 on 2026-03-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0003_alter_tablereservation_status_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantdatamodel',
            name='price_range',
            field=models.CharField(blank=True, choices=[('₹', 'Budget-Friendly'), ('₹₹', 'Moderate'), ('₹₹₹', 'Expensive'), ('₹₹₹₹', 'Very Expensive')], default='₹₹', max_length=10, null=True),
        ),
    ]
