# Generated by Django 6.0.2 on 2026-03-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_restaurantdatamodel_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantdatamodel',
            name='total_tables',
        ),
        migrations.AddField(
            model_name='restaurantdatamodel',
            name='tables_10_capacity',
            field=models.PositiveIntegerField(default=1, help_text='Number of 10-guest tables'),
        ),
        migrations.AddField(
            model_name='restaurantdatamodel',
            name='tables_4_capacity',
            field=models.PositiveIntegerField(default=5, help_text='Number of 4-guest tables'),
        ),
        migrations.AddField(
            model_name='restaurantdatamodel',
            name='tables_6_capacity',
            field=models.PositiveIntegerField(default=2, help_text='Number of 6-guest tables'),
        ),
        migrations.AddField(
            model_name='restaurantdatamodel',
            name='tables_8_capacity',
            field=models.PositiveIntegerField(default=2, help_text='Number of 8-guest tables'),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='table_capacity',
            field=models.PositiveIntegerField(default=4, help_text='The capacity of the table booked (4, 6, 8, 10)'),
        ),
    ]
