# Generated by Django 6.0.2 on 2026-03-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0007_remove_restaurantdatamodel_total_tables_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantdatamodel',
            name='area',
            field=models.CharField(max_length=500),
        ),
    ]
