# Generated by Django 6.0.2 on 2026-03-27 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0009_reviewimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdatamodel',
            name='closing_time',
            field=models.TimeField(default='22:00:00'),
        ),
        migrations.AddField(
            model_name='restaurantdatamodel',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='restaurantdatamodel',
            name='opening_time',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='number_of_guests',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='Table Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
