# Generated by Django 6.0.2 on 2026-03-28 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0010_restaurantdatamodel_closing_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereservation',
            name='status',
            field=models.CharField(choices=[('Table Pending', 'Table Pending'), ('Your Table Is Ready', 'Your Table Is Ready'), ('completed', 'Completed'), ('cancelled', 'cancelled')], default='Table Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_reservations', to=settings.AUTH_USER_MODEL),
        ),
    ]
