# Generated by Django 6.0.2 on 2026-04-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0011_alter_tablereservation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantdatamodel',
            name='extra_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant/extra'),
        ),
        migrations.AddField(
            model_name='restaurantdatamodel',
            name='tables_2_capacity',
            field=models.PositiveIntegerField(default=5, help_text='Number of 2-guest tables'),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='has_baby',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='table_selection',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tablereservation',
            name='total_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='table_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
