# Generated by Django 6.0.2 on 2026-02-21 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_is_verified_remove_user_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Hotel', 'Hotel'), ('Restaurant', 'Restaurant'), ('Saloon', 'Saloon'), ('User', 'User'), ('Business', 'Business')], default='User', max_length=20),
        ),
    ]
