# Generated by Django 6.0.2 on 2026-03-17 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_passwordresetotp_id_alter_user_id'),
        ('users', '0009_pendinguser'),
    ]

    operations = [
    ]
