# Generated by Django 6.0.2 on 2026-02-08 10:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotel_owner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='HotelDataModel',
        ),
    ]
