# Generated by Django 6.0.2 on 2026-02-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_rename_hotel_hoteldatamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldatamodel',
            name='environment_image',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/environment/'),
        ),
        migrations.AddField(
            model_name='hoteldatamodel',
            name='room_image1',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/rooms/'),
        ),
        migrations.AddField(
            model_name='hoteldatamodel',
            name='room_image2',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/rooms/'),
        ),
        migrations.AlterField(
            model_name='hoteldatamodel',
            name='badge',
            field=models.CharField(choices=[('Luxury Stays', 'Luxury Stays'), ('Cheap & Best', 'Cheap & Best'), ('Dormitory', 'Dormitory')], max_length=50),
        ),
    ]
