# Generated by Django 6.0.2 on 2026-02-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_hoteldatamodel_total_rooms_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldatamodel',
            name='amenities',
            field=models.JSONField(blank=True, default=list, help_text="List of amenities (e.g., ['WiFi', 'Pool', 'Gym'])"),
        ),
    ]
