# Generated by Django 6.0.2 on 2026-02-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_hoteldatamodel_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_guests',
            field=models.PositiveIntegerField(default=1, help_text='Number of guests (max 3 per room)'),
        ),
        migrations.AddField(
            model_name='booking',
            name='rooms_booked',
            field=models.PositiveIntegerField(default=1, help_text='Number of rooms required (auto-calculated: 3 guests per room)'),
        ),
        migrations.AlterField(
            model_name='hoteldatamodel',
            name='amenities',
            field=models.JSONField(blank=True, default=list, help_text='List of amenities in JSON format: ["WiFi", "Pool", "Gym"]'),
        ),
    ]
