# Generated by Django 6.0.2 on 2026-02-10 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0008_booking_number_of_guests_booking_rooms_booked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='number_of_guests',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='rooms_booked',
        ),
        migrations.RemoveField(
            model_name='hoteldatamodel',
            name='amenities',
        ),
    ]
