# Generated by Django 6.0.2 on 2026-02-10 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_remove_booking_number_of_guests_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_guests',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='booking',
            name='rooms_booked',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
