# Generated by Django 6.0.2 on 2026-02-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_booking_number_of_guests_booking_rooms_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldatamodel',
            name='amenities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
