# Generated by Django 6.0.2 on 2026-02-17 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_hoteldatamodel_amenities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteldatamodel',
            name='badge',
            field=models.CharField(blank=True, choices=[('Luxury Stays', 'Luxury Stays'), ('Cheap & Best', 'Cheap & Best'), ('Dormitory', 'Dormitory')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='hoteldatamodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/'),
        ),
        migrations.AlterField(
            model_name='hoteldatamodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='hoteldatamodel',
            name='total_rooms',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Total number of rooms available for this hotel/category', null=True),
        ),
        migrations.CreateModel(
            name='HotelGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hotels/gallery/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='hotels.hoteldatamodel')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(default=0)),
                ('total_rooms', models.PositiveIntegerField(default=1)),
                ('bed_type', models.CharField(blank=True, max_length=50, null=True)),
                ('room_size', models.CharField(blank=True, max_length=50, null=True)),
                ('amenities', models.TextField(blank=True, help_text='Comma separated list of amenities', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotels/rooms/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hoteldatamodel')),
            ],
        ),
    ]
