# Generated by Django 6.0.2 on 2026-02-19 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_booking_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_size',
        ),
    ]
