# Generated by Django 6.0.2 on 2026-02-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_remove_room_room_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='room_type_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
