# Generated by Django 6.0.2 on 2026-02-19 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0015_booking_room_type_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoteldatamodel',
            name='total_rooms',
        ),
    ]
