# Generated by Django 6.0.2 on 2026-03-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0016_remove_hoteldatamodel_total_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
