# Generated by Django 6.0.2 on 2026-03-12 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0017_booking_payment_status_booking_razorpay_order_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearbyAttraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='Distance from hotel in kilometers', max_digits=5)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_attractions', to='hotels.hoteldatamodel')),
            ],
        ),
    ]
