# Generated by Django 6.0.2 on 2026-03-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0019_alter_booking_id_alter_hoteldatamodel_id_and_more'),
        ('hotels', '0019_hotelreview'),
    ]

    operations = [
    ]
