# Generated by Django 6.0.2 on 2026-03-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0021_alter_booking_id_alter_hoteldatamodel_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteldatamodel',
            name='keywords',
            field=models.TextField(blank=True, help_text='Keywords for search optimization (comma separated)', null=True),
        ),
        migrations.AddField(
            model_name='hoteldatamodel',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hoteldatamodel',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
