# Generated by Django 6.0.2 on 2026-03-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0024_reviewimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='discount_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
