# Generated by Django 6.0.2 on 2026-04-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0026_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_children',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
