# Generated by Django 6.0.2 on 2026-04-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0029_alter_hoteldatamodel_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteldatamodel',
            name='badge',
            field=models.CharField(blank=True, choices=[('Luxury Stays', 'Luxury Stays'), ('Cheap & Best', 'Cheap & Best'), ('Dormitory', 'Dormitory'), ('Beach Resort', 'Beach Resort'), ('Eco Stay', 'Eco Stay')], max_length=50, null=True),
        ),
    ]
