# Generated by Django 6.0.2 on 2026-04-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salondatamodel',
            name='closing_time',
            field=models.TimeField(default='21:00:00'),
        ),
        migrations.AddField(
            model_name='salondatamodel',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='salondatamodel',
            name='opening_time',
            field=models.TimeField(default='09:00:00'),
        ),
    ]
