# Generated by Django 6.0.2 on 2026-04-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_salondatamodel_closing_time_salondatamodel_is_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salondatamodel',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='salondatamodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salondatamodel',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
