# Generated by Django 6.0.2 on 2026-04-24 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0003_alter_salondatamodel_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalonGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='salons/gallery/')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='salons.salondatamodel')),
            ],
        ),
    ]
