# Generated by Django 6.0.2 on 2026-04-26 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0005_salonqueueentry_guest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonqueueentry',
            name='services',
            field=models.ManyToManyField(related_name='queue_entries_multi', to='salons.salonservice'),
        ),
        migrations.AlterField(
            model_name='salonqueueentry',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salons.salonservice'),
        ),
    ]
