# Generated by Django 6.0.2 on 2026-04-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0006_salonqueueentry_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salonqueueentry',
            name='service_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
