# Generated by Django 6.0.2 on 2026-04-16 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking', 'Booking'), ('reservation', 'Reservation'), ('failure', 'Failure'), ('info', 'Information')], default='info', max_length=20),
        ),
    ]
